layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  linkedin: craigsetera
  youtube: csetera
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url

historical:
  - name: Compute Magazine Article (1984)
    web_url: https://archive.org/details/1984-02-compute-magazine/page/n63/mode/2up
    image_url: /assets/images/compute.png

  - name: setera.org (Archive)
    web_url: /assets/archives/www.setera.org/
    image_url: /assets/images/setera.org.png

  - name: eclipseme.org (Archive)
    web_url: /assets/archives/www.setera.org/eclipsemeorg/
    image_url: /assets/images/eclipseme.org.png

topics:
  - name: 3D Printing
    web_url: https://en.wikipedia.org/wiki/3D_printing
    image_url: https://cdn.shopify.com/s/files/1/0046/3781/8929/products/ender-3-pro_1_960x.jpg?v=1625023890
    
  - name: Arduino
    web_url: https://github.com/topics/arduino
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/arduino/arduino.png

  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/cpp/cpp.png

  - name: Electron
    web_url: https://github.com/topics/electron
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/electron/electron.png

  - name: ESP8266
    web_url: https://en.wikipedia.org/wiki/ESP8266
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/ESP-01.jpg/440px-ESP-01.jpg

  # - name: Front End Development
  #   web_url: https://github.com/topics/frontend
  #   image_url: /assets/images/web-tech-employed.jpg

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png

  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/raspberry-pi/raspberry-pi.png

  - name: REST APIs
    web_url: https://github.com/topics/rest-api
    image_url: https://upload.wikimedia.org/wikipedia/commons/9/92/Cog_font_awesome.svg

  - name: Spring Boot
    web_url: https://github.com/topics/spring-boot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png

  - name: Typescript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png

  - name: Ubuntu
    web_url: https://github.com/topics/ubuntu
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ubuntu/ubuntu.png

  - name: Vue.js
    web_url: https://github.com/topics/vue
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png

  - name: Web Applications
    web_url: https://github.com/topics/webapp
    image_url: /assets/images/web-tech-employed.jpg
